### ISSUE TITLE
Bookings

### ISSUE THREAD

**Issue by heimanchan** [heimanchan/Paradise-City-Full-Stack-Project#4]
- [x] Logged in users can book a spot through booking form
- [x] User can view their bookings in their profile page
- [x] User can cancel their booking in their profile page
- [x] Adequate styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds to demonstrate the feature

**Comment by ryan-mapa** [comment]
- [ ] Add a call to login when attempting to book

**Comment by heimanchan** [comment]
required login for booking is implemented
